/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.applets;

import javax.swing.JOptionPane;

/**
 *
 * @author pc lenovo
 */
public class BotonesApplet extends javax.swing.JFrame {

    /**
     * Creates new form BotonesApplet
     */
    public BotonesApplet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldNumero2 = new javax.swing.JTextField();
        jTextFieldNumero1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonResta = new javax.swing.JButton();
        jButtonSuma = new javax.swing.JButton();
        jButtonRaizY = new javax.swing.JButton();
        jButtonDvide = new javax.swing.JButton();
        jButtonLimpia = new javax.swing.JButton();
        jMultiplica = new javax.swing.JButton();
        jButtonRaiz1 = new javax.swing.JButton();
        jButtonmayor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número 1");

        jLabel2.setText("Número 2");

        jButtonResta.setText("Resta");
        jButtonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestaActionPerformed(evt);
            }
        });

        jButtonSuma.setText("Sumar ");
        jButtonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumaActionPerformed(evt);
            }
        });

        jButtonRaizY.setText("Raiz 2");
        jButtonRaizY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRaizYActionPerformed(evt);
            }
        });

        jButtonDvide.setText("Divide");
        jButtonDvide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDvideActionPerformed(evt);
            }
        });

        jButtonLimpia.setText("Limpia");
        jButtonLimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiaActionPerformed(evt);
            }
        });

        jMultiplica.setText("Multiplicación");
        jMultiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMultiplicaActionPerformed(evt);
            }
        });

        jButtonRaiz1.setText("Raiz 1");
        jButtonRaiz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRaiz1ActionPerformed(evt);
            }
        });

        jButtonmayor.setText("Mayor");
        jButtonmayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmayorActionPerformed(evt);
            }
        });

        jLabel3.setText("Resultado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonmayor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonLimpia, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(81, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonRaiz1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRaizY, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jMultiplica, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDvide, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNumero1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNumero2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(38, 38, 38))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSuma)
                    .addComponent(jButtonResta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDvide)
                    .addComponent(jMultiplica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRaizY)
                    .addComponent(jButtonRaiz1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonmayor)
                    .addComponent(jButtonLimpia))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestaActionPerformed
        
        if (jTextFieldNumero1.getText() == null || jTextFieldNumero1.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Inserte un número en el campo 1", "información",
                    JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
            
        } else if (jTextFieldNumero2.getText() == null || jTextFieldNumero2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Inserte un número en el campo 2", "información",
                    JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
            
        } else {
            if (isNumeric()) {
                
                resultado = Integer.parseInt(jTextFieldNumero1.getText())
                        - Integer.parseInt(jTextFieldNumero2.getText());
                jTextFieldResultado.setText(String.valueOf(resultado));
            }
        }
        

    }//GEN-LAST:event_jButtonRestaActionPerformed

    private void jButtonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumaActionPerformed
        
        if (jTextFieldNumero1.getText() == null || jTextFieldNumero1.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Inserte un número en el campo 1", "información",
                    JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
            
        } else if (jTextFieldNumero2.getText() == null || jTextFieldNumero2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Inserte un número en el campo 2", "información",
                    JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
            
        } else {
            if (isNumeric()) {
                
                resultado = Integer.parseInt(jTextFieldNumero1.getText())
                        + Integer.parseInt(jTextFieldNumero2.getText());
                jTextFieldResultado.setText(String.valueOf(resultado));
            }
        }
    }//GEN-LAST:event_jButtonSumaActionPerformed

    private void jButtonRaizYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRaizYActionPerformed
        
        if (jTextFieldNumero2.getText() == null || jTextFieldNumero2.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Inserte un número en el campo 2", "información",
                    JOptionPane.WARNING_MESSAGE);            
            
        } else {
            validar = 2;
            if (isNumeric()) {
                resultado2 = Math.sqrt(Double.parseDouble(jTextFieldNumero2.getText()));
                jTextFieldResultado.setText(String.valueOf(resultado2));                
                
            }
            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRaizYActionPerformed

    private void jButtonDvideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDvideActionPerformed
        if (jTextFieldNumero1.getText() == null || jTextFieldNumero1.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Inserte un número en el campo 1", "información",
                    JOptionPane.WARNING_MESSAGE); //Tipo de mensaje

        } else if (jTextFieldNumero2.getText() == null || jTextFieldNumero2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Inserte un número en el campo 2", "información",
                    JOptionPane.WARNING_MESSAGE); //Tipo de mensaje

        } else {
            if (isNumeric()) {
                
                try {
                    resultado = Integer.parseInt(jTextFieldNumero1.getText())
                            / Integer.parseInt(jTextFieldNumero2.getText());
                    jTextFieldResultado.setText(String.valueOf(resultado));
                } catch (ArithmeticException a) {
                    JOptionPane.showMessageDialog(null, "Error división por 0 corrija", "información",
                            JOptionPane.ERROR_MESSAGE); //Tipo de mensaje

                }
            }
        }
    }//GEN-LAST:event_jButtonDvideActionPerformed

    private void jButtonLimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiaActionPerformed
        jTextFieldNumero1.setText("");
        jTextFieldNumero2.setText("");
        jTextFieldResultado.setText("");
    }//GEN-LAST:event_jButtonLimpiaActionPerformed

    private void jMultiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMultiplicaActionPerformed
        
        if (jTextFieldNumero1.getText() == null || jTextFieldNumero1.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Inserte un número en el campo 1", "información",
                    JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
            
        } else if (jTextFieldNumero2.getText() == null || jTextFieldNumero2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Inserte un número en el campo 2", "información",
                    JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
            
        } else {
            if (isNumeric()) {
                
                resultado = Integer.parseInt(jTextFieldNumero1.getText())
                        * Integer.parseInt(jTextFieldNumero2.getText());
                jTextFieldResultado.setText(String.valueOf(resultado));
            }
        }
        
    }//GEN-LAST:event_jMultiplicaActionPerformed

    private void jButtonRaiz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRaiz1ActionPerformed
        
        if (jTextFieldNumero1.getText() == null || jTextFieldNumero1.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Inserte un número en el campo 1", "información",
                    JOptionPane.WARNING_MESSAGE);            
            
        } else {
            validar = 1;
            if (isNumeric()) {
                resultado2 = Math.sqrt(Double.parseDouble(jTextFieldNumero1.getText()));
                jTextFieldResultado.setText(String.valueOf(resultado2));                
                
            }
            
        }
    }//GEN-LAST:event_jButtonRaiz1ActionPerformed

    private void jButtonmayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmayorActionPerformed
        
        if (jTextFieldNumero1.getText() == null || jTextFieldNumero1.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Inserte un número en el campo 1", "información",
                    JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
            
        } else if (jTextFieldNumero2.getText() == null || jTextFieldNumero2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Inserte un número en el campo 2", "información",
                    JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
            
        } else {
            if (jTextFieldNumero1.getText().equalsIgnoreCase(jTextFieldNumero2.getText())) {
                JOptionPane.showMessageDialog(null, "los números no pueden ser iguales", "información",
                        JOptionPane.WARNING_MESSAGE); //Tipo de mensaje

            } else {
                if (isNumeric()) {

                    jTextFieldResultado.setText(String.valueOf(Math.max(Integer.parseInt(jTextFieldNumero1.getText()),
                            Integer.parseInt(jTextFieldNumero2.getText()))));

                }
            }
        }        
    }//GEN-LAST:event_jButtonmayorActionPerformed
    
    private boolean isNumeric() {
        
        boolean validacion = false;
        try {
            
            if (validar == 1) {
                Double.parseDouble(jTextFieldNumero1.getText());
                validacion = true;
            } else if (validar == 2) {
                Double.parseDouble(jTextFieldNumero2.getText());
                
            } else {
                Integer.parseInt(jTextFieldNumero1.getText());
                Integer.parseInt(jTextFieldNumero2.getText());
                validacion = true;
            }
            
        } catch (NumberFormatException nfe) {
            
            JOptionPane.showMessageDialog(null, "Debe ingresar un número", "Error",
                    JOptionPane.ERROR_MESSAGE); //Tipo de mensaje
            
        }
        return validacion;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BotonesApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BotonesApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BotonesApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BotonesApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BotonesApplet().setVisible(true);
            }
        });
    }
    
    private Integer resultado = 0;
    private int validar = 0;
    private Double resultado2 = 0.0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDvide;
    private javax.swing.JButton jButtonLimpia;
    private javax.swing.JButton jButtonRaiz1;
    private javax.swing.JButton jButtonRaizY;
    private javax.swing.JButton jButtonResta;
    private javax.swing.JButton jButtonSuma;
    private javax.swing.JButton jButtonmayor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jMultiplica;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldNumero1;
    private javax.swing.JTextField jTextFieldNumero2;
    private javax.swing.JTextField jTextFieldResultado;
    // End of variables declaration//GEN-END:variables
}
